# https://github.com/GitGuardian
# https://github.com/GitGuardian/ggshield-action/issues/22 -- Post findings too webhook coming soon *(hopefully)*

name: GitGuardian scan

on: 
  push:
  pull_request:
  workflow_dispatch: # Edited base file too able to run it manually
  schedule: #Every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  scanning:
    name: GitGuardian scan
    runs-on: ubuntu-latest # https://cdn.nest.rip/uploads/ccb5db80-8949-4bff-b691-33c9e40ef775.png
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: GitGuardian scan
        uses: GitGuardian/ggshield-action@v1
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}