name: Compress Images

on:
    pull_request:
        paths:
            - "**/*.svg"
            - "**/*.png"
            - "**/*.jpg"
            - "**/*.jpeg"
            - "**/*.gif"
            - "**/*.webp"
            - "**/*.avif"

jobs:
    build:
        if: github.event.pull_request.head.repo.full_name == github.repository
        name: cadamsdev/image-optimizer-action
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Compress Images
              id: compress-images
              uses: cadamsdev/image-optimizer-action@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Create New Pull Request If Needed
              if: steps.compress-images.outputs.markdown_report != ''
              uses: peter-evans/create-pull-request@v5
              with:
                  title: Compressed Images
                  branch-suffix: timestamp
                  commit-message: Compressed Images
                  body: ${{ steps.compress-images.outputs.markdown_report }}
