name: 'Lock Threads'

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
